apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: 1-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: 1-component
    app.kubernetes.io/part-of: purple-mermaid-app
  name: 1-component
  namespace: beaumorley
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: 1-component
    weight: 100
status: {}
